# Changes here will be overwritten by Copier
_commit: 86aebd8
_src_path: .
copyright_year: '2024'
documentation: true
email: cuinixam@me.com
full_name: cuinixam
github_username: cuinixam
open_source_license: MIT
package_name: py_app_dev
project_name: Python App Development
project_short_description: My application development modules.
project_slug: py-app-dev

